import fs from 'fs';
import path from 'path';
import { OpenCodeSession } from '../plugin/storage-reader';
import { SummarizedSession } from '../summarizer/types';
import { ModularSummarizer } from '../summarizer/modular-summarizer';
import { ConfigManager } from '../core/config';
import { AgeEncryption } from '../encryption/age';
import { buildHandoffDocument } from './handoff-build';
import { HandoffDocument, HandoffGenerateResult } from './handoff-types';

function loadSessionFromRepo(sessionsDir: string): OpenCodeSession | SummarizedSession | null {
  if (!fs.existsSync(sessionsDir)) return null;

  const files = fs.readdirSync(sessionsDir)
    .filter(f => f.endsWith('.json') || f.endsWith('.age'))
    .map(f => ({ name: f, mtime: fs.statSync(path.join(sessionsDir, f)).mtimeMs }))
    .sort((a, b) => b.mtime - a.mtime);

  if (files.length === 0) return null;

  const latest = files[0].name;
  const filePath = path.join(sessionsDir, latest);

  let raw: string;
  if (latest.endsWith('.age')) {
    raw = AgeEncryption.decrypt(filePath);
  } else {
    raw = fs.readFileSync(filePath, 'utf-8');
  }

  return JSON.parse(raw);
}

function formatHandoffMarkdown(
  session: OpenCodeSession | SummarizedSession,
  summarized: SummarizedSession
): string {
  const date = new Date().toISOString();
  const { summary, decisions, key_files, next_steps } = summarized.content;

  const sessionFile = `session-${session.id}.summary.json.age`;

  return `# AI Session Handoff

> Generated by Relay at ${date}
> Session: \`${session.id}\` | Project: \`${session.project}\`

## For the assistant (read first)

This file is **memory from a previous AI session**, not an automatic execution plan.

1. **Explain** to the user in plain language (2–4 paragraphs): what was done, what is pending, and project state.
2. **Do not** run commands, explore the repo, or edit files until the user explicitly asks.
3. **Ask** what they want to do next at the end.

If the user only attached this file, your first reply must be that explanation plus a question — do not start implementing.

---

## Summary

${summary}

## Decisions

${decisions.length ? decisions.map(d => `- ${d}`).join('\n') : '- (none detected)'}

## Key files

${key_files.length ? key_files.map(f => `- \`${f}\``).join('\n') : '- (none detected)'}

## Pending (orientative — do not execute alone)

${next_steps.length ? next_steps.map(s => `- ${s}`).join('\n') : '- User will indicate the next step in this chat.'}

---

*Complements \`context.md\` / \`AGENTS.md\` (project manual). This file = last AI session state.*

Encrypted transcript: \`relay decrypt .ai-memory/sessions/${sessionFile}\`

Machine-readable: \`.ai-memory/HANDOFF.json\` (schema v1)
`;
}

export async function generateHandoff(
  session?: OpenCodeSession | SummarizedSession,
  options: { fromRepo?: boolean; outputPath?: string } = {}
): Promise<HandoffGenerateResult> {
  const cwd = process.cwd();
  const memoryDir = path.join(cwd, '.ai-memory');
  const sessionsDir = path.join(memoryDir, 'sessions');
  const mdPath = options.outputPath || path.join(memoryDir, 'HANDOFF.md');
  const jsonPath = options.outputPath
    ? options.outputPath.replace(/\.md$/i, '.json')
    : path.join(memoryDir, 'HANDOFF.json');

  let targetSession = session;

  if (!targetSession && options.fromRepo) {
    targetSession = loadSessionFromRepo(sessionsDir) || undefined;
  }

  if (!targetSession) {
    throw new Error('No session available. Run `relay sync` or pass a session.');
  }

  const config = ConfigManager.load();
  const summarizer = new ModularSummarizer(config?.summarizer || { provider: 'local' });

  let summarized: SummarizedSession;
  if ('isSummary' in targetSession && targetSession.isSummary) {
    summarized = targetSession;
  } else {
    summarized = await summarizer.toSummary(targetSession as OpenCodeSession);
  }

  const markdown = formatHandoffMarkdown(targetSession, summarized);
  const handoffJson = buildHandoffDocument(targetSession, summarized, { memoryDir });

  if (!fs.existsSync(memoryDir)) {
    fs.mkdirSync(memoryDir, { recursive: true });
  }

  fs.writeFileSync(mdPath, markdown, 'utf-8');
  fs.writeFileSync(jsonPath, JSON.stringify(handoffJson, null, 2), 'utf-8');

  return { mdPath, jsonPath };
}

/** Read HANDOFF.json from project if present */
export function readHandoffJson(projectRoot: string = process.cwd()): HandoffDocument | null {
  const jsonPath = path.join(projectRoot, '.ai-memory', 'HANDOFF.json');
  if (!fs.existsSync(jsonPath)) return null;
  try {
    return JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
  } catch {
    return null;
  }
}

/** Read HANDOFF.md from project if present */
export function readHandoffMarkdown(projectRoot: string = process.cwd()): string | null {
  const mdPath = path.join(projectRoot, '.ai-memory', 'HANDOFF.md');
  if (!fs.existsSync(mdPath)) return null;
  return fs.readFileSync(mdPath, 'utf-8');
}

export function listSessionFilesMeta(projectRoot: string = process.cwd()): Array<{
  fileName: string;
  sizeBytes: number;
  mtimeMs: number;
}> {
  const sessionsDir = path.join(projectRoot, '.ai-memory', 'sessions');
  if (!fs.existsSync(sessionsDir)) return [];

  return fs
    .readdirSync(sessionsDir)
    .filter(f => f.endsWith('.age') || f.endsWith('.json'))
    .map(fileName => {
      const full = path.join(sessionsDir, fileName);
      const stat = fs.statSync(full);
      return { fileName, sizeBytes: stat.size, mtimeMs: stat.mtimeMs };
    })
    .sort((a, b) => b.mtimeMs - a.mtimeMs);
}
